import React, { Component } from "react"

class PopUp extends Component {
  handleClick = () => {
    this.props.toggle()
  }

  render() {
    return (
      <div>
        <div className="modal_content">
          <span className="close" onClick={this.handleClick}>
            &times;
          </span>
          <form>
            <div>
             <p>
                <a
                  href="https://www.servealabama.gov/covid19"
                  target="blank">
                  Alabama
                </a>         
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://alaska.providence.org/services/volunteer"
                  target="blank"
                >
                  Alaska
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.handsonphoenix.org/covid19?layoutViewMode=tablet"
                  target="blank"
                >
                  Arizona
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.volunteerar.org/?layoutViewMode=tablet"
                  target="blank"
                >
                  Arkansas
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.californiavolunteers.ca.gov/get-involved/covid-19/"
                  target="blank"
                >
                  California
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.sparkthechangecolorado.org/covid19resources?layoutViewMode=tablet"
                  target="blank"
                >
                  Colorado
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://portal.ct.gov/Coronavirus/Information-For/Volunteers"
                  target="blank"
                >
                  Connecticut
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://volunteer.delaware.gov/?layoutViewMode=tablet"
                  target="blank"
                >
                  Delaware
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.volunteerflorida.org/covid/"
                  target="blank"
                >
                  Florida
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://dph.georgia.gov/press-releases/2020-03-24/volunteer-covid-19-response"
                  target="blank"
                >
                  Georgia
                </a>
              </p>
            </div>
            <div>
              <p>
                <a href="https://auw.galaxydigital.com/" target="blank">
                  Hawaii
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://coronavirus.idaho.gov/how-to-help/"
                  target="blank"
                >
                  Idaho
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://serveillinois.galaxydigital.com/"
                  target="blank"
                >
                  Illinois
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://uwci.org/united-ways-covid-19-volunteer-response/"
                  target="blank"
                >
                  Indiana
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://volunteeriowa.galaxydigital.com/"
                  target="blank"
                >
                  Iowa
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.volunteeruwgkc.com/_landing/crisis-volunteer-guide/"
                  target="blank"
                >
                  Kansas
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://serve.ky.gov/disaster/Pages/COVID-19.aspx"
                  target="blank"
                >
                  Kentucky
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://volunteerlouisiana.gov/disaster-services"
                  target="blank"
                >
                  Louisiana
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.maine.gov/covid19/maine-helps"
                  target="blank"
                >
                  Maine
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://governor.maryland.gov/marylandunites/"
                  target="blank"
                >
                  Maryland
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.volunteermatch.org/covid19"
                  target="blank"
                >
                  Massachusetts
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.michigan.gov/coronavirus/0,9753,7-406-98178_98811---,00.html"
                  target="blank"
                >
                  Michigan
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://mn.gov/covid19/for-minnesotans/volunteer/"
                  target="blank"
                >
                  Minnesota
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.volunteermississippi.ms.gov/"
                  target="blank"
                >
                  Mississippi
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.stlvolunteer.org/covid19?layoutViewMode=tablet"
                  target="blank"
                >
                  Missouri
                </a>
              </p>
            </div>
            <div>
              <p>
                 <a
                  href="https://www.serve.nebraska.gov/"
                  target="blank">
                  Nebraska
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://nevadavolunteers.org/get-involved/"
                  target="blank"
                >
                  Nevada
                </a>
              </p>
            </div>
            <div>
              <p>
                <a href="https://volunteernh.org/" target="blank">
                  New Hampshire
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.nj.gov/state/volunteer-in-nj.shtml"
                  target="blank"
                >
                  New Jersey
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.newmexico.gov/2020/03/17/heres-how-you-can-help-during-covid-19/"
                  target="blank"
                >
                  New Mexico
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www1.nyc.gov/site/helpnownyc/index.page"
                  target="blank"
                >
                  New York
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.nc.gov/volunteer/volunteer-opportunities"
                  target="blank"
                >
                  North Carolina
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.volunteermatch.org/search/orgs.jsp?r=region&categories=23&l=North+Dakota%2C+USA"
                  target="blank"
                >
                  North Dakota
                </a>
              </p>
            </div>
            <div>
              <p>
                <a href="https://www.voaohin.org/covid-19" target="blank">
                  Ohio
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="http://www.volunteercentraloklahoma.org/"
                  target="blank"
                >
                  Oklahoma
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.oregon.gov/highered/institutions-programs/workforce/Pages/Oregon-volunteering.aspx"
                  target="blank"
                >
                  Oregon
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.uwp.org/member/member-information/knowledge-cafe/coronavirus-covid-19-hub/covid-19-volunteer-information-resources/"
                  target="blank"
                >
                  Pennsylvania
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://health.ri.gov/covid/howtohelp/"
                  target="blank"
                >
                  Rhode Island
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.uwasc.org/volunteer-south-carolina"
                  target="blank"
                >
                  South Carolina
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://doh.sd.gov/providers/preparedness/volunteer.aspx"
                  target="blank"
                >
                  South Dakota
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.tn.gov/volunteer-tennessee.html"
                  target="blank"
                >
                  Tennessee
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="http://onestarfoundation.org/coronavirus/"
                  target="blank"
                >
                  Texas
                </a>
              </p>
            </div>
            <div>
              <p>
                <a href="https://coronavirus.utah.gov/help/" target="blank">
                  Utah
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://www.vermont.gov/volunteer#gsc.tab=0"
                  target="blank"
                >
                  Vermont
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="http://virginiaservice.virginia.gov/volunteering/volunteer-centers/"
                  target="blank"
                >
                  Virginia
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://covid19helpwa.org/volunteer/"
                  target="blank"
                >
                  Washington
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="https://volunteer.wv.gov/Volunteer/Pages/Covid-19.aspx"
                  target="blank"
                >
                  West Virginia
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="http://volunteerwisconsin.galaxydigital.com/"
                  target="blank"
                >
                  Wisconsin
                </a>
              </p>
            </div>
            <div>
              <p>
                <a
                  href="http://www.volunteerwyoming.org/need/index?s=1&need_init_id=3038"
                  target="blank"
                >
                  Wyoming
                </a>
              </p>
            </div>
          </form>
        </div>
      </div>
    )
  }
}

export default PopUp
